# Generated by Django 6.1 on 2026-08-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsposting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
